# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get audit case
#'
#' This endpoint contains Final Audit Reports approved by the Commission since inception. The search can be based on information about the audited committee (Name, FEC ID Number, Type, Election Cycle) or the issues covered in the report.
#'
#' @inheritParams fec_call_api
#' @param audit_case_id Primary/foreign key for audit tables
#' @param cycle Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year.
#' @param sub_category_id The finding id of an audit. Finding are a category of broader issues. Each category has an unique ID.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param min_election_cycle Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year.
#' @param audit_id The audit issue. Each subcategory has an unique ID
#' @param q The name of the committee. If a committee changes its name, the most recent name will be shown. Committee names are not unique. Use committee_id for looking up records.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param max_election_cycle Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param committee_type The one-letter type code of the organization: - C communication cost - D delegate - E electioneering communication - H House - I independent expenditure filer (not a committee) - N PAC - nonqualified - O independent expenditure-only (super PACs) - P presidential - Q PAC - qualified - S Senate - U single candidate independent expenditure - V PAC with non-contribution account, nonqualified - W PAC with non-contribution account, qualified - X party, nonqualified - Y party, qualified - Z national party non-federal account
#' @param qq Name of candidate running for office
#' @param page For paginating through results, starting at page 1
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param committee_designation Type of committee: - H or S - Congressional - P - Presidential - X or Y or Z - Party - N or Q - PAC - I - Independent expenditure - O - Super PAC
#' @param primary_category_id Audit category ID (table PK)
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort Provide a field to sort by. Use `-` for descending order. ex: `-case_no`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_audit_case <- function(audit_case_id, cycle, sub_category_id, sort_nulls_last, sort_hide_null, min_election_cycle, audit_id, q, per_page, max_election_cycle, candidate_id, committee_type, qq, page, committee_id, committee_designation, primary_category_id, sort_null_only, sort, api_key = Sys.getenv("FEC_API_KEY")) {
  fec_call_api(
    path = "/audit-case/",
    api_key = api_key,
    query = list(audit_case_id = audit_case_id, cycle = cycle, sub_category_id = sub_category_id, sort_nulls_last = sort_nulls_last, sort_hide_null = sort_hide_null, min_election_cycle = min_election_cycle, audit_id = audit_id, q = q, per_page = per_page, max_election_cycle = max_election_cycle, candidate_id = candidate_id, committee_type = committee_type, qq = qq, page = page, committee_id = committee_id, committee_designation = committee_designation, primary_category_id = primary_category_id, sort_null_only = sort_null_only, sort = sort)
  )
}

#' Get audit category
#'
#' This lists the options for the categories and subcategories available in the /audit-search/ endpoint.
#'
#' @inheritParams fec_call_api
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param primary_category_name Primary Audit Category - No Findings or Issues/Not a Committee - Net Outstanding Campaign/Convention Expenditures/Obligations - Payments/Disgorgements - Allocation Issues - Prohibited Contributions - Disclosure - Recordkeeping - Repayment to US Treasury - Other - Misstatement of Financial Activity - Excessive Contributions - Failure to File Reports/Schedules/Notices - Loans - Referred Findings Not Listed
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param primary_category_id Audit category ID (table PK)
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_audit_category <- function(sort_nulls_last, page, primary_category_name, sort_hide_null, primary_category_id, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY")) {
  fec_call_api(
    path = "/audit-category/",
    api_key = api_key,
    query = list(sort_nulls_last = sort_nulls_last, page = page, primary_category_name = primary_category_name, sort_hide_null = sort_hide_null, primary_category_id = primary_category_id, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get audit primary category
#'
#' This lists the options for the primary categories available in the /audit-search/ endpoint.
#'
#' @inheritParams fec_call_api
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param primary_category_name Primary Audit Category - No Findings or Issues/Not a Committee - Net Outstanding Campaign/Convention Expenditures/Obligations - Payments/Disgorgements - Allocation Issues - Prohibited Contributions - Disclosure - Recordkeeping - Repayment to US Treasury - Other - Misstatement of Financial Activity - Excessive Contributions - Failure to File Reports/Schedules/Notices - Loans - Referred Findings Not Listed
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param primary_category_id Audit category ID (table PK)
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_audit_primary_category <- function(sort_nulls_last, page, primary_category_name, sort_hide_null, primary_category_id, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY")) {
  fec_call_api(
    path = "/audit-primary-category/",
    api_key = api_key,
    query = list(sort_nulls_last = sort_nulls_last, page = page, primary_category_name = primary_category_name, sort_hide_null = sort_hide_null, primary_category_id = primary_category_id, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get names audit candidates
#'
#' Search for candidates or committees by name. If you're looking for information on a particular person or group, using a name to find the `candidate_id` or `committee_id` on this endpoint can be a helpful first step.
#'
#' @inheritParams fec_call_api
#' @param q Name (candidate or committee) to search for
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_names_audit_candidates <- function(q, api_key = Sys.getenv("FEC_API_KEY")) {
  fec_call_api(
    path = "/names/audit_candidates/",
    api_key = api_key,
    query = list(q = q)
  )
}

#' Get names audit committees
#'
#' Search for candidates or committees by name. If you're looking for information on a particular person or group, using a name to find the `candidate_id` or `committee_id` on this endpoint can be a helpful first step.
#'
#' @inheritParams fec_call_api
#' @param q Name (candidate or committee) to search for
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_names_audit_committees <- function(q, api_key = Sys.getenv("FEC_API_KEY")) {
  fec_call_api(
    path = "/names/audit_committees/",
    api_key = api_key,
    query = list(q = q)
  )
}
