# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' addBoards()
#'
#' BKTODO: No description provided.
#'
#' @inheritParams trello_call_api
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
trello_add_boards <- function(
    key = Sys.getenv("TRELLO_KEY"),
    token = Sys.getenv("TRELLO_TOKEN")) {
  trello_call_api(
    path = "/boards",
    method = "post",
    key = key, token = token
  )
}
