# These functions were generated by the {beekeeper} package, based on
# components@security_schemes from the source API description. You may want to
# delete unused options. In addition, APIs often have additional security
# options that are not formally documented in the API description. For example,
# for any `location = query` `api_key` options, it might be possible to instead
# pass the same parameter in a header, possibly with a different name. Consult
# the text description of authentication in your API documentation.

trello_security <- function(req, key = NULL, token = NULL) {
  if (!is.null(key)) {
    req <- trello_security_api_key(req, key)
  }
  if (!is.null(token)) {
    req <- trello_security_api_token(req, token)
  }
  return(req)
}

# An API key provided by the API provider. This key is not clearly documented in the API description. Check the API documentation for details.
trello_security_api_key <- function(req, key) {
  nectar::security_api_key(
    req,
    location = "query",
    parameter_name = "key",
    api_key = key
  )
}

# An API key provided by the API provider. This key is not clearly documented in the API description. Check the API documentation for details.
trello_security_api_token <- function(req, token) {
  nectar::security_api_key(
    req,
    location = "query",
    parameter_name = "token",
    api_key = token
  )
}
