# These functions were generated by the {beekeeper} package, based on
# components@security_schemes from the source API description. You may want to
# delete unused options. In addition, APIs often have additional security
# options that are not formally documented in the API description. For example,
# for any `location = query` `api_key` options, it might be possible to instead
# pass the same parameter in a header, possibly with a different name. Consult
# the text description of authentication in your API documentation.

{{api_abbr}}_security <- function(req, {{security_arg_names}}) {
  {{#api_schemes}}
  req <- {{api_abbr}}_security_{{name}}(req, {{arg_name}})
  {{/api_schemes}}
  return(req)
}

{{#security_schemes}}
{{#description}}
# {{description}}
{{/description}}
{{api_abbr}}_security_{{name}} <- function(req, {{#api_key}}{{arg_name}}) {
  nectar::security_api_key(
    req,
    location = "{{location}}",
    parameter_name = "{{parameter_name}}",
    api_key = {{arg_name}}
  )
}{{/api_key}}

{{/security_schemes}}
