# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

{{#paths}}
#' {{summary}}
#'
#' {{description}}
#' {{#has_security}}
#' @inheritParams {{api_abbr}}_call_api{{/has_security}}{{#params}}
#' @param {{name}} {{{description}}}{{/params}}
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
{{api_abbr}}_{{operation_id}} <- function({{{args}}}{{{security_signature}}}) {
  {{api_abbr}}_call_api(
    path = {{{path}}}
  )
}

{{/paths}}
