#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom cli cli_warn
#' @importFrom desc desc
#' @importFrom fs is_dir
#' @importFrom fs path
#' @importFrom fs path_dir
#' @importFrom fs path_file
#' @importFrom fs path_rel
#' @importFrom glue glue
#' @importFrom glue glue_collapse
#' @importFrom httptest2 use_httptest2
#' @importFrom lubridate now
#' @importFrom lubridate parse_date_time
#' @importFrom nectar call_api
#' @importFrom nectar stabilize_string
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map2
#' @importFrom purrr pmap
#' @importFrom purrr quietly
#' @importFrom rapid as_rapid
#' @importFrom rapid class_api_key_security_scheme
#' @importFrom rapid class_security_scheme_details
#' @importFrom rapid class_security_schemes
#' @importFrom rlang .data
#' @importFrom rlang set_names
#' @importFrom rlang try_fetch
#' @importFrom rprojroot find_package_root_file
#' @importFrom S7 class_any
#' @importFrom snakecase to_snake_case
#' @importFrom stringr str_remove
#' @importFrom styler style_file
#' @importFrom testthat test_that
#' @importFrom usethis proj_get
#' @importFrom usethis proj_path
#' @importFrom usethis use_build_ignore
#' @importFrom usethis use_directory
#' @importFrom usethis use_package
#' @importFrom usethis use_template
#' @importFrom usethis use_testthat
#' @importFrom utils capture.output
#' @importFrom yaml read_yaml
#' @importFrom yaml write_yaml
## usethis namespace: end
NULL
