#' Use a beekeeper config file to generate code
#'
#' Creates or updates package files based on the information in a beekeeper
#' config file (generated by [use_beekeeper()] or manually). The files enforce
#' an opinionated framework for API packages.
#'
#' @param config_file The path to a beekeeper yaml file.
#' @param pkg_agent A string to identify this package, for use in the
#'   `user_agent` argument of [nectar::call_api()].
#'
#' @return `TRUE` invisibly.
#' @export
generate_pkg <- function(config_file = "_beekeeper.yml",
                         pkg_agent = generate_pkg_agent(config_file)) {
  .assert_is_pkg()
  config <- .read_config(config_file)
  api_definition <- readRDS(
    fs::path(fs::path_dir(config_file), config$rapid_file)
  )

  # This will be a series of functions, each of which generates one or more
  # files.
  .generate_call(
    api_title = config$api_title,
    api_abbr = config$api_abbr,
    base_url = api_definition@servers@url,
    pkg_agent = pkg_agent
  )

  return(invisible(TRUE))
}

.generate_call <- function(api_title,
                           api_abbr,
                           base_url,
                           pkg_agent) {
  api_title <- stbl::stabilize_chr_scalar(
    api_title,
    allow_null = FALSE,
    allow_zero_length = FALSE,
    allow_na = FALSE
  )
  api_abbr <- stbl::stabilize_chr_scalar(
    api_abbr,
    allow_null = FALSE,
    allow_zero_length = FALSE,
    allow_na = FALSE
  )
  base_url <- stbl::stabilize_chr_scalar(
    base_url,
    allow_null = FALSE,
    allow_zero_length = FALSE,
    allow_na = FALSE
  )
  pkg_agent <- stbl::stabilize_chr_scalar(
    pkg_agent,
    allow_null = FALSE,
    allow_zero_length = FALSE,
    allow_na = FALSE
  )

  usethis::use_directory("R")
  usethis::use_package("nectar")

  data_for_call <- list(
    api_title = api_title,
    api_abbr = api_abbr,
    base_url = base_url,
    pkg_agent = pkg_agent
  )

  template <- "010-call.R"

  # Eventually this will also include a test-generator.
  .bk_use_template(
    template = template,
    data = data_for_call
  )
  return(invisible(TRUE))
}


#' Use a template in this package
#'
#' @param template The name of the template.
#' @param dir The directory where the file should be created.
#' @param data A list of variables to apply to the template.
#'
#' @return The path to the generated or updated file, invisibly.
#' @keywords internal
.bk_use_template <- function(template,
                             dir = c("R", "tests/testthat"),
                             data) {
  dir <- match.arg(dir)
  target <- usethis::proj_path(dir, template)
  save_as <- fs::path_rel(target, usethis::proj_path())

  usethis::use_template(
    template = template,
    save_as = save_as,
    data = data,
    package = "beekeeper"
  )
  utils::capture.output({
    styler::style_file(target)
  })

  return(invisible(target))
}
