#' Use a beekeeper config file to generate code
#'
#' Creates or updates package files based on the information in a beekeeper
#' config file (generated by [use_beekeeper()] or manually). The files enforce
#' an opinionated framework for API packages.
#'
#' @param config_file The path to a beekeeper yaml file.
#' @param pkg_agent A string to identify this package, for use in the
#'   `user_agent` argument of [nectar::call_api()].
#'
#' @return A character vector of paths to files that were added or updated,
#'   invisibly.
#' @export
generate_pkg <- function(config_file = "_beekeeper.yml",
                         pkg_agent = generate_pkg_agent(config_file)) {
  .assert_is_pkg()
  config <- .read_config(config_file)
  api_definition <- .read_api_definition(config_file, config$rapid_file)
  .prepare_r()
  touched_files <- .generate_basics(config, api_definition, pkg_agent)
  return(invisible(touched_files))
}

.read_api_definition <- function(config_file, rapid_file) {
  readRDS(
    fs::path(fs::path_dir(config_file), rapid_file)
  )
}

.generate_basics <- function(config, api_definition, pkg_agent) {
  security_data <- .generate_security(
    config$api_abbr,
    api_definition@components@security_schemes
  )

  data <- list(
    api_title = nectar::stabilize_string(config$api_title),
    api_abbr = nectar::stabilize_string(config$api_abbr),
    base_url = nectar::stabilize_string(api_definition@servers@url),
    pkg_agent = nectar::stabilize_string(pkg_agent)
  )
  data <- c(data, security_data)

  touched_files <- c(
    .bk_use_template(
      template = "010-call.R",
      data = data
    ),
    .bk_use_template(
      template = "test-010-call.R",
      dir = "tests/testthat",
      data = list(api_abbr = config$api_abbr)
    )
  )
  return(invisible(touched_files))
}

.prepare_r <- function() {
  usethis::use_directory("R")
  usethis::use_testthat()
  purrr::quietly(httptest2::use_httptest2)()
  usethis::use_package("nectar")
  usethis::use_package("beekeeper", type = "Suggests")
}

#' Use a template in this package
#'
#' @param template The name of the template.
#' @param dir The directory where the file should be created.
#' @param data A list of variables to apply to the template.
#'
#' @return The path to the generated or updated file, invisibly.
#' @keywords internal
.bk_use_template <- function(template,
                             dir = c("R", "tests/testthat"),
                             data) {
  dir <- match.arg(dir)
  target <- usethis::proj_path(dir, template)
  save_as <- fs::path_rel(target, usethis::proj_path())

  usethis::use_template(
    template = template,
    save_as = save_as,
    data = data,
    package = "beekeeper"
  )
  utils::capture.output({
    styler::style_file(target)
  })

  return(invisible(target))
}
