# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' List all APIs
#'
#' List all APIs in the directory. Returns links to the OpenAPI definitions for each API in the directory. If API exist in multiple versions `preferred` one is explicitly marked. Some basic info from the OpenAPI definition is cached inside each object. This allows you to generate some simple views without needing to fetch the OpenAPI definition for each API.
#'
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
guru_list_apis <- function() {
  guru_call_api(
    path = "/list.json",
    method = "get"
  )
}

#' Get basic metrics
#'
#' Some basic metrics for the entire directory. Just stunning numbers to put on a front page and are intended purely for WoW effect :)
#'
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
guru_get_metrics <- function() {
  guru_call_api(
    path = "/metrics.json",
    method = "get"
  )
}

#' List all providers
#'
#' List all the providers in the directory
#'
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
guru_get_providers <- function() {
  guru_call_api(
    path = "/providers.json",
    method = "get"
  )
}

#' Retrieve one version of a particular API
#'
#' Returns the API entry for one specific version of an API where there is no serviceName.
#'
#' @param provider BKTODO: No description provided.
#' @param api BKTODO: No description provided.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
guru_get_api <- function(provider, api) {
  guru_call_api(
    path = c("/specs/{provider}/{api}.json", provider = provider, api = api),
    method = "get"
  )
}

#' Retrieve one version of a particular API with a serviceName.
#'
#' Returns the API entry for one specific version of an API where there is a serviceName.
#'
#' @param provider BKTODO: No description provided.
#' @param service BKTODO: No description provided.
#' @param api BKTODO: No description provided.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
guru_get_service_api <- function(provider, service, api) {
  guru_call_api(
    path = c("/specs/{provider}/{service}/{api}.json", provider = provider, service = service, api = api),
    method = "get"
  )
}

#' List all APIs for a particular provider
#'
#' List all APIs in the directory for a particular providerName Returns links to the individual API entry for each API.
#'
#' @param provider BKTODO: No description provided.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
guru_get_provider <- function(provider) {
  guru_call_api(
    path = c("/{provider}.json", provider = provider),
    method = "get"
  )
}

#' List all serviceNames for a particular provider
#'
#' List all serviceNames in the directory for a particular providerName
#'
#' @param provider BKTODO: No description provided.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
guru_get_services <- function(provider) {
  guru_call_api(
    path = c("/{provider}/services.json", provider = provider),
    method = "get"
  )
}
