#' Configure a package to use beekeeper
#'
#' Create a configuration file for a package to use beekeeper. The configuration
#' file tracks information that will be used for generation of other functions,
#' and the timestamp when the configuration was last updated or used.
#'
#' @inheritParams rlang::args_dots_empty
#' @param x An object to use to define the configuration. It must be
#'   translatable to a [rapid::class_rapid()] object by [rapid::as_rapid()]. Usually
#'   this will be a url pointing to an OpenAPI document, or a list generated by
#'   reading such a document.
#' @param api_abbr A short (about 2-5 letter) abbreviation for the API, for use
#'   in function names and environment variables.
#' @param config_file The path to which the configuration should be written.
#' @param rapid_file The path to which the R API definition (rapid) object
#'   should be written.
#'
#' @return The path to the configuration file, invisibly. The config file is
#'   written as a side effect of this function. The rapid object is also
#'   written, and the path to that file is saved in the config file.
#' @export
use_beekeeper <- function(x,
                          api_abbr,
                          ...,
                          config_file = "_beekeeper.yml",
                          rapid_file = "_beekeeper_rapid.rds") {
  x <- as_rapid(x)
  api_abbr <- stabilize_string(api_abbr)
  config_file <- stabilize_string(config_file)
  rapid_file <- stabilize_string(rapid_file)
  saveRDS(x, rapid_file)

  use_build_ignore(c(config_file, rapid_file))

  write_yaml(
    list(
      api_title = x@info@title,
      api_abbr = api_abbr,
      api_version = x@info@version,
      rapid_file = path_rel(rapid_file, path_dir(config_file)),
      updated_on = as.character(now(tzone = "UTC"))
    ),
    file = config_file
  )
  return(invisible(config_file))
}

.read_config <- function(config_file = "_beekeeper.yml") {
  config <- read_yaml(config_file)
  config$updated_on <- parse_date_time(
    config$updated_on,
    orders = c("ymd HMS", "ymd H", "ymd")
  )
  return(config)
}
